### ISSUE TITLE
Shanghai hardfork config failure, does not support EIP-1559

### ISSUE THREAD

**Issue by antazoey** [NomicFoundation/hardhat#4176]
### Version of Hardhat

2.12.7

### What happened?

I ran this command:

```
/Users/me/path/to/hardhat node --hostname 127.0.0.1 --port 8545 --config /Users/me/.ape/hardhat/hardhat.config.js --show-stack-traces
```

and my config looks like this:

```yaml
// See https://hardhat.org/config/ for config options.
module.exports = {
  networks: {
    hardhat: {
      hardfork: "shanghai",
      // Base fee of 0 allows use of 0 gas price when testing
      initialBaseFeePerGas: 0,
      accounts: {
        mnemonic: "test test test test test test test test test test test junk",
        path: "m/44'/60'/0'",
        count: 10
      }
    },
  },
};
```

and I get this error:

```
  * Invalid value {"hardfork":"shanghai","initialBaseFeePerGas":0,"accounts":{"mnemonic":"test test test test test test test test test test test junk","path":"m/44'/60'/0'","count":10}} for HardhatConfig.networks.hardhat - Expected a value of type HardhatNetworkConfig.
  * Unexpected config HardhatConfig.networks.hardhat.initialBaseFeePerGas found - This field is only valid for networks with EIP-1559. Try a newer hardfork or remove it.

To learn more about Hardhat's configuration, please go to https://hardhat.org/config/
    at validateConfig (/Users/me/ApeProjects/yearn-vaults-v3/node_modules/hardhat/src/internal/core/config/config-validation.ts:367:9)
    at loadConfigAndTasks (/Users/me/ApeProjects/yearn-vaults-v3/node_modules/hardhat/src/internal/core/config/config-loading.ts:94:17)
    at main (/Users/me/ApeProjects/yearn-vaults-v3/node_modules/hardhat/src/internal/cli/cli.ts:199:62)
```

### Minimal reproduction steps

1. Create a config same as from What Happened in a hidden dir in your home dir
2. Run the command from the *What happened* section

### Search terms

config hardfork shanghai basefee gas
